spring.application.name=crypto-project

spring.datasource.url=jdbc:postgresql://postgres:5432/crypto
spring.datasource.username=crypto_user
spring.datasource.password=crypto_pass
spring.datasource.driver-class-name=org.postgresql.Driver


# Do not allow Hibernate to attempt schema generation on your existing DB
spring.jpa.hibernate.ddl-auto=none

# Use Hibernate community SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# show SQL in logs if you want
spring.jpa.show-sql=false

server.port=8080

