spring.application.name=crypto-project
# SQLite DB path inside container
spring.datasource.url=jdbc:sqlite:/data/crypto_daily.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Do not allow Hibernate to attempt schema generation on your existing DB
spring.jpa.hibernate.ddl-auto=none

# Use Hibernate community SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# show SQL in logs if you want
spring.jpa.show-sql=false

server.port=8080

