spring.application.name=crypto-project

spring.datasource.url=jdbc:postgresql://kriptoserver.postgres.database.azure.com:5432/crypto?sslmode=require
spring.datasource.username=adminmartina
spring.datasource.password=Andrejcar123!
spring.datasource.driver-class-name=org.postgresql.Driver


# Do not allow Hibernate to attempt schema generation on your existing DB
spring.jpa.hibernate.ddl-auto=none

# Use Hibernate community SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# show SQL in logs if you want
spring.jpa.show-sql=false

server.port=8080

